---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: "schema_graph/static/schema_graph/main.js"
      - id: flake8
      - id: trailing-whitespace
        exclude: "schema_graph/static/schema_graph/main.js"

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
        language_version: "python3"

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        language_version: "python3"
        entry: black
        types: [python]
