---
name: Release to PyPI

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install JS dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build python package
        run: |
          ./verify-version.sh
          yarn run build
          poetry build

      - name: Upload to PyPI
        env:
          POETRY_HTTP_BASIC_PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish
